version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.04
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker ps
  deploy:
    docker:
      - image: cimg/base:2023.04
    resource_class: xlarge
    steps:
      - checkout
      - run: echo "Hello World!"

workflows:
  test-workflow:
    jobs:
      - build
      - deploy:
          type: approval
