version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.04
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker ps

workflows:
  test-workflow:
    jobs:
      - build
